name: "Develop pipeline for RUUUUUUUuuuby"

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      
      - name: Install Dependencies
        run: bundle install

      - name: Lynter
        run: gem install rubocop && bundle exec rubocop

      - name: Scan for Vulns
        run: gem install bundler-audit && bundler-audit update && bundler-audit check

      - name: Run unit tests
        run: bundle exec rspec

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/ruby-app:develop

      
      